# Generated by Django 3.1.2 on 2020-10-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('source', 'language', 'value')},
        ),
    ]
