# Generated by Django 3.1.2 on 2020-10-02 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0002_auto_20201002_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='value',
            field=models.TextField(default='TBD'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together={('target', 'author')},
        ),
    ]
